services:
  25rp20014-php:
    build: .
    container_name: 25rp20014-php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - 25rp20014-mysql

  25rp20014-mysql:
    image: mysql:8.0
    container_name: 25rp20014-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  25rp20014-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 25rp20014-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: 25rp20014-mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - 25rp20014-mysql

volumes:
  mysql_data: